### ISSUE TITLE
Functions query_time, query_generator, query_sql gone

### ISSUE THREAD

**Issue by bradystoll** [NREL/rplexos#61]
These functions (among others) exist in version 1.1.11 and are gone in 1.1.12. I can't seem to find where they were deleted and why @danielsjf ?

**Comment by danielsjf** [comment]
@bradystoll they are available in the namespace: https://github.com/NREL/rplexos/blob/master/NAMESPACE

Also, if I browse through the package documentation, I can see them there. In any case nothing was removed on purpose.

Could you give more information on what you mean with gone?

**Comment by danielsjf** [comment]
In the latest github version, the examples of query_sql() also seem to work.

**Comment by bradystoll** [comment]
Ah, I believe that is the issue. I had updated to the version 1.1.12 right before it was removed from cran. When I installed the github version those functions still appear to work. Thanks for the clarification

**Comment by danielsjf** [comment]
@bradystoll yes the CRAN remove is quite unfortunate, but it is due to issues with the linux builds. I cannot reproduce them since I don't have a linux environment available.

It is strange that you got 1.1.12 from CRAN since the latest version there is 1.1.11. Maybe it was a buggy github version :-)

**Comment by bradystoll** [comment]
Gotcha. Good to know!
