### ISSUE TITLE
Package ‘rplexos’ was removed from the CRAN repository

### ISSUE THREAD

**Issue by monnedepraetere** [NREL/rplexos#63]
See [https://cran.r-project.org/web/packages/rplexos/index.html](url)

**Comment by monnedepraetere** [comment]
Also, I have downloaded the .gz file from the archive at CRAN and tried installing it directly (am using R version 3.4.1) using following command:

`install.packages("C:\\Users\\rplexos_1.1.11.tar.gz",repos = NULL, type = "source")`

which resulted in following error: 

`ERROR: dependencies 'Rcpp', 'dplyr', 'RSQLite', 'DBI', 'data.table', 'tidyr', 'lubridate', 'stringi', 'doParallel', 'foreach' are not available for package 'rplexos'`

**Comment by danielsjf** [comment]
@monnedepraetere Yes that it very unfortunate. It is related to issue https://github.com/NREL/rplexos/issues/60. There is a bug in rplexos on Linux and until this is resolved, they won't accept it anymore on CRAN. Unfortunately I don't have a Linux distribution available for testing.

The bug you get is probably due to missing dependencies. You can just install those packages from CRAN. Alternatively you can install the latest version directly from github with the package devtools. This should also install the dependencies.

```
devtools::install_github("NREL/rplexos")
```

**Comment by monnedepraetere** [comment]
Thanks a lot, @danielsjf that worked!
